# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/generated/**
    - .github/workflows/**

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    library_annotations: true
    one_member_abstracts: true
    use_super_parameters: true
    super_goes_last: true
    matching_super_parameters: true
    prefer_const_constructors: true # Enforces const constructors
    prefer_const_literals_to_create_immutables: true # Enforces const literals
