name: jintent
description: "https://github.com/GenSoftMX/JIntent"
version: 1.0.0+2
homepage: https://github.com/GenSoftMX/JIntent
environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0