name: jintent
description: "jintent is a Flutter package that provides an architecture for managing state changes in your application using the concept of intents."
version: 1.0.1
homepage: https://github.com/GenSoftMX/JIntent
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0